name: GeminiChatPlugin
version: '1.3'
main: com.LanRhyme.geminiChatPlugin.GeminiChatPlugin
api-version: '1.21'
load: STARTUP
authors: [ LanRhyme ]
description: 将Gemini大模型接入Minecraft服务器
commands:
  switchpreset:
    description: 切换预设
    usage: /switchpreset <预设名称>
    permissions: gemini.switchpreset
  presetmenu:
    description: 打开预设选择菜单
    usage: /presetmenu